sudo:
  required

language: bash

services:
  - docker

before_script:
  - export DOCKER_TAG="${TRAVIS_TAG:-latest}"
  - bash ci/before-script.bash
  - export DOCKER_IMAGE="$DOCKER_REPOSITORY:$DOCKER_TAG"
  # - docker pull hvksmr1996/jupyter-complete:latest

script:
  - docker build . -t "$DOCKER_IMAGE" # --cache-from hvksmr1996/jupyter-complete:latest

deploy:
  provider: script
  script: bash ci/docker-push.bash
  on:
    branch: master
    tags: true
