sudo:
  required

language: bash

branches:
  except:
    - draft
    - tmp
    - /.*\.(draft|tmp)$/
    - /^(draft|tmp)\..*/
    - docker
    - dockerhub
    - dockercloud
    - latest

services:
  - docker

before_script:
  - export GIT_TAG="$TRAVIS_BRANCH"
  - export DOCKER_TAG="$TRAVIS_BRANCH"
  - export DOCKER_IMAGE="$DOCKER_REPOSITORY:$DOCKER_TAG"
  - export DOCKER_LATEST="$DOCKER_REPOSITORY:latest"
  - bash ci/before-script.bash
  - docker pull hvksmr1996/jupyter-complete:latest

script:
  - bash ci/docker-build.bash
  - bash ci/docker-push.bash
