sudo:
  required

language: bash

branches:
  except:
    - draft
    - tmp
    - /.*\.(draft|tmp)$/
    - /^(draft|tmp)\..*/
    - docker
    - dockerhub
    - dockercloud

services:
  - docker

before_script:
  - export DOCKER_TAG="${TRAVIS_TAG:-latest}"
  - bash ci/before-script.bash
  - export DOCKER_IMAGE="$DOCKER_REPOSITORY:$DOCKER_TAG"
  - docker pull hvksmr1996/jupyter-complete:latest

script:
  - bash ci/docker-build.bash
  - bash ci/docker-push.bash
